image: node:lts

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  CI: "false"
  AWS_DEFAULT_REGION: "eu-central-1"

  DEV_S3_BUCKET_NAME: "shopify-storefront-dev"
  DEV_PUBLIC_URL: $DEV_PUBLIC_URL
  DEV_API_URL: $DEV_API_URL
  DEV_AWS_PROJECT_REGION: $DEV_AWS_PROJECT_REGION
  DEV_AWS_COGNITO_IDENTITY_POOL_ID: $DEV_AWS_COGNITO_IDENTITY_POOL_ID
  DEV_AWS_COGNITO_REGION: $DEV_AWS_COGNITO_REGION
  DEV_AWS_USER_POOLS_ID: $DEV_AWS_USER_POOLS_ID
  DEV_AWS_USER_POOLS_WEB_CLIENT_ID: $DEV_AWS_USER_POOLS_WEB_CLIENT_ID
  DEV_REACT_APP_ANON_USERNAME: $DEV_ANON_USERNAME
  DEV_REACT_APP_ANON_PASSWORD: $DEV_ANON_PASSWORD

  PROD_S3_BUCKET_NAME: "shopify-storefront-master"
  PROD_PUBLIC_URL: $PROD_PUBLIC_URL
  PROD_API_URL: $PROD_API_URL
  PROD_AWS_PROJECT_REGION: $PROD_AWS_PROJECT_REGION
  PROD_AWS_COGNITO_IDENTITY_POOL_ID: $PROD_AWS_COGNITO_IDENTITY_POOL_ID
  PROD_AWS_COGNITO_REGION: $PROD_AWS_COGNITO_REGION
  PROD_AWS_USER_POOLS_ID: $PROD_AWS_USER_POOLS_ID
  PROD_AWS_USER_POOLS_WEB_CLIENT_ID: $PROD_AWS_USER_POOLS_WEB_CLIENT_ID
  PROD_REACT_APP_ANON_USERNAME: $PROD_ANON_USERNAME
  PROD_REACT_APP_ANON_PASSWORD: $PROD_ANON_PASSWORD

stages:
  - build
  - deploy

before_script:
  - apt update && apt -y install awscli

build_dev:
  stage: build
  script:
    - npm install
    - REACT_APP_PUBLIC_URL="$PROD_PUBLIC_URL" REACT_APP_API_URL="https://api.scircula.com" REACT_APP_AWS_PROJECT_REGION="$PROD_AWS_PROJECT_REGION" REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID="$DEV_AWS_COGNITO_IDENTITY_POOL_ID" REACT_APP_AWS_COGNITO_REGION="$DEV_AWS_COGNITO_REGION" REACT_APP_AWS_USER_POOLS_ID="$DEV_AWS_USER_POOLS_ID" REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID="$DEV_AWS_USER_POOLS_WEB_CLIENT_ID" REACT_APP_ANON_USERNAME="$DEV_REACT_APP_ANON_USERNAME" REACT_APP_ANON_PASSWORD="$DEV_REACT_APP_ANON_PASSWORD" npm run build
    # - REACT_APP_PUBLIC_URL="$DEV_PUBLIC_URL" REACT_APP_API_URL="$DEV_API_URL" REACT_APP_AWS_PROJECT_REGION="$DEV_AWS_PROJECT_REGION" REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID="$DEV_AWS_COGNITO_IDENTITY_POOL_ID" REACT_APP_AWS_COGNITO_REGION="$DEV_AWS_COGNITO_REGION" REACT_APP_AWS_USER_POOLS_ID="$DEV_AWS_USER_POOLS_ID" REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID="$DEV_AWS_USER_POOLS_WEB_CLIENT_ID" REACT_APP_ANON_USERNAME="$DEV_REACT_APP_ANON_USERNAME" REACT_APP_ANON_PASSWORD="$DEV_REACT_APP_ANON_PASSWORD" npm run build
  artifacts:
    paths:
      - build
  only:
    - /^SOF-.*$/
    - main

deploy_dev:
  stage: deploy
  dependencies:
    - build_dev
  script:
    - S3_BUCKET_NAME="$DEV_S3_BUCKET_NAME" npm run deploy
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id EFTDC8SKWUUZP --paths "/*"
  only:
    - /^SOF-.*$/
    - main

build_main:
  stage: build
  script:
    - npm install --only-production
    - REACT_APP_PUBLIC_URL="$PROD_PUBLIC_URL" REACT_APP_API_URL="$PROD_API_URL" REACT_APP_AWS_PROJECT_REGION="$PROD_AWS_PROJECT_REGION" REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID="$PROD_AWS_COGNITO_IDENTITY_POOL_ID" REACT_APP_AWS_COGNITO_REGION="$PROD_AWS_COGNITO_REGION" REACT_APP_AWS_USER_POOLS_ID="$PROD_AWS_USER_POOLS_ID" REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID="$PROD_AWS_USER_POOLS_WEB_CLIENT_ID" REACT_APP_ANON_USERNAME="$PROD_REACT_APP_ANON_USERNAME" REACT_APP_ANON_PASSWORD="$PROD_REACT_APP_ANON_PASSWORD" npm run build
  artifacts:
    paths:
      - build
  only:
    - main

deploy_main:
  stage: deploy
  dependencies:
    - build_main
  script:
    - S3_BUCKET_NAME="$PROD_S3_BUCKET_NAME" npm run deploy
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id E1REHCK4WQC6SU --paths "/*"
  only:
    - main
